**Class Work**

**Assignment**

**Q.1** Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [4]:
import numpy as np

arr = np.arange(1, 6)
print("Original Array:", arr)

print("Addition (+2):", arr + 2)
print("Multiplication (*3):", arr * 3)
print("Division (/2):", arr / 2)

print("\nArray Properties:")
print("Type:", type(arr))
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)

print("\nSpecial Arrays:")
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Empty:\n", np.empty((2, 3)))

Original Array: [1 2 3 4 5]
Addition (+2): [3 4 5 6 7]
Multiplication (*3): [ 3  6  9 12 15]
Division (/2): [0.5 1.  1.5 2.  2.5]

Array Properties:
Type: <class 'numpy.ndarray'>
Data Type: int64
Dimensions: 1
Shape: (5,)

Special Arrays:
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Empty:
 [[1. 1. 1.]
 [1. 1. 1.]]


**Q.2** Questions on Basic NumPy Array:

**a)** Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [5]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed Array:", arr[::-1])

Reversed Array: [5 4 6 3 2 1]


**Q.2**

**b)** Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(arr):
    elems, counts = np.unique(arr, return_counts=True)
    most_common = elems[np.argmax(counts)]
    indices = np.where(arr == most_common)[0]
    return most_common, indices

most_common_x, indices_x = most_frequent(x)
print(f"Most Frequent in x: {most_common_x}, Indices: {indices_x}")

most_common_y, indices_y = most_frequent(y)
print(f"Most Frequent in y: {most_common_y}, Indices: {indices_y}")

Most Frequent in x: 1, Indices: [0 5 7 8 9]
Most Frequent in y: 1, Indices: [0 1 2]


**Q.3** For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [7]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


**Q.4** Write program to create an 1-D NumPy array named <<\Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace().

Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array.

 Find the transpose of this array using reshape() attribute.

Can we do the same with T attribute?

In [2]:
import numpy as np
VaibhavGupta = np.linspace(10, 100, 25)

print("Array:", VaibhavGupta)
print("Dimensions:", VaibhavGupta.ndim)
print("Shape:", VaibhavGupta.shape)
print("Total elements:", VaibhavGupta.size)
print("Data type:", VaibhavGupta.dtype)
print("Bytes per element:", VaibhavGupta.itemsize)
print("Total bytes:", VaibhavGupta.nbytes)

reshaped_array = VaibhavGupta.reshape(25, 1)
print("Reshaped Array:\n", reshaped_array)
print("Transpose using reshape:\n", reshaped_array.T)

# Transpose using .T is ineffective as it's a 1D array
print("Transpose using .T:", VaibhavGupta.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Bytes per element: 8
Total bytes: 200
Reshaped Array:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using reshape:
 [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using .T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


**Q5.** Create a 2-D Array of three rows and four columns, named ucs420_<\your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements.

 Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<\your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<\your_name>>.

In [3]:
import numpy as np

ucs420_VaibhavGupta = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]).reshape(3,4)

print("Original Array:\n", ucs420_VaibhavGupta)
print("Mean:", np.mean(ucs420_VaibhavGupta))
print("Median:", np.median(ucs420_VaibhavGupta))
print("Max:", np.max(ucs420_VaibhavGupta))
print("Min:", np.min(ucs420_VaibhavGupta))

unique_elements, counts = np.unique(ucs420_VaibhavGupta, return_counts=True)
print("Unique Elements:", unique_elements)
print("Their Count:", counts)

reshaped_ucs420_VaibhavGupta = ucs420_VaibhavGupta.reshape(4,3)
print("Reshaped (4x3):\n", reshaped_ucs420_VaibhavGupta)

resized_ucs420_VaibhavGupta = ucs420_VaibhavGupta.copy()
resized_ucs420_VaibhavGupta.resize(2,3)
print("Resized (2x3):\n", resized_ucs420_VaibhavGupta)

Original Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Their Count: [1 1 2 1 1 1 1 1 1 1 1]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3):
 [[10 20 30]
 [40 50 60]]
